### ISSUE TITLE
Running Terminals: Edit Configuration command for the first time gives error message

### ISSUE THREAD

**Issue by sabriele** [fabiospampinato/vscode-terminals#1]
_Hi there, I'd just like to preface this by saying that I know this probably isn't a bug and is most likely just a result of me not knowing how to install extensions properly in VS Code because I'm just getting started with it._ 

After installing Terminals (directly from the button on the sidebar) and running the `Terminals: Edit Configuration` command for the first time, I get the error message shown at the top of the screenshot ("You have to open a project before being able to edit its configuration").

![screenshot 2017-08-23 17 05 02](https://user-images.githubusercontent.com/4678102/29607997-790c21b8-8825-11e7-83aa-62ad925e61ec.png)

What does it mean to "open a project" and how can I go about solving this? Would manually creating a `terminals.json` file under the `.vscode` directory help?

Additionally, other extensions I have installed so far are:
```
"Tyriar.terminal-tabs",
"dangelov.theme-monokaigravity",
"dbaeumer.vscode-eslint",
"eg2.tslint",
"fabiospampinato.vscode-terminals",
"zhuangtongfa.Material-theme"
```

Thank you so much for your help in advance!

**Comment by fabiospampinato** [comment]
`Terminals: Edit configuration` will create a configuration file under your currently opened folder path. You're seeing that error because you didn't open any folder.

**Comment by sabriele** [comment]
I understand now. Again, sorry about that and thank you!

**Comment by fabiospampinato** [comment]
No problem.

I hope you'll like the extension :) let me know if you have some ideas about new features 👍
