### ISSUE TITLE
Support for setting environment variables

### ISSUE THREAD

**Issue by fabiospampinato** [fabiospampinato/vscode-terminals#10]
VSC's [API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Terminal) supports setting environment variables, we should also support them.

**Comment by M-Zuber** [comment]
I'd be interested in trying to get this in, where would you suggest I start?

**Comment by fabiospampinato** [comment]
@M-Zuber The code could certainly be written better, but it shouldn't be too hard to add support for this. You'll basically have to:

1. Get the `env` [here](https://github.com/fabiospampinato/vscode-terminals/blob/master/src/run.ts#L58), deconstructing a terminal's configuration object.
2. Replace [this](https://github.com/fabiospampinato/vscode-terminals/blob/master/src/run.ts#L78) `vscode.window.createTerminal` call, passing all the arguments in an object instead, as this is the only supported way to pass environment variables to the terminal instance. Read more about this [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#1673) and [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TerminalOptions).
3. Add the `env` object you retrieved at step 1 to the object you're passing to `vscode.window.createTerminal`.

That should work.

**Comment by M-Zuber** [comment]
So...
In order for this to work, we will need to upgrade the engine to `^1.18.0`
