### ISSUE TITLE
Consider renaming extension?

### ISSUE THREAD

**Issue by Tyriar** [fabiospampinato/vscode-terminals#11]
I think you might find more success if the extension name was a little more descriptive, "terminals" is very generic and could be anything, "restore terminals" for example is much more understandable at a glance.

Note I don't mean changing the ID (`name`), just the `displayName`.

**Comment by fabiospampinato** [comment]
It's not all about restoring terminals though, it can also work as a task runner of sorts, one can execute a bunch of commands through it on demand.

In the future I'll also add support for auto-discovering npm/gulp/grunt tasks, so I prefer to keep the name generic.

I'll add "restore" to the keywords though, thanks for the suggestion.

**Comment by Tyriar** [comment]
Still it's *very* generic, you might be missing out on installs. Maybe "Enhanced/Advanced Terminal" or something to that effect would be more fitting then?

**Comment by fabiospampinato** [comment]
Or maybe "Terminals Manager" 🤔

I quite like minimal names though, if I rename this one I should probably also rename some others:

```
Commands => StatusBar Commands
Todo+ => Todo Tasks 
Projects+ => Projects Manager
Diff => Diff Files
Bump => Bump Version
```

If those names weren't already taken I wouldn't even have used those "+"s.

I don't care all that much about installs to be honest, as they are counted by the marketplace they are also not very meaningful, I could publish a pointless extension and 1 million updates to it and even if I'm it's only user the counter in the marketplace would be 1 million.

I'll ponder on this. I'll probably try "Terminals Manager" and see how it goes, how does that sound to you?

**Comment by Tyriar** [comment]
Sounds better 😃

**Comment by fabiospampinato** [comment]
Renamed to `Terminals Manager` in v1.9.0.
