### ISSUE TITLE
how about tab support?

### ISSUE THREAD

**Issue by jaycapps** [fabiospampinato/vscode-terminals#16]
How about tabs?
"terminals": [
  {
    "name": "foo",
    "tabify": true,
  },
 {
    "name": "bar",
    "tabify": true,
    "tabname": "bar tab"
  },
],
"tabgroups":  [
 {
    "name": "foobar",
    "tabs":   ["foo","bar tab"],
    "color":  "yellow",
 }
],

**Comment by fabiospampinato** [comment]
Tabs? Terminal tabs aren't support in VSC https://github.com/Microsoft/vscode/issues/10546.

If you mean something different please clarify.
