### ISSUE TITLE
[Enhancement Suggestion] Is it possible to "Edit Configuration" automatically?

### ISSUE THREAD

**Issue by yangshuairocks** [fabiospampinato/vscode-terminals#17]
Is it possible to `Edit Configuration` automatically when the user invokes `Run Single` or `Run` and there is no configuration file? That would be nice and a little bit more user-friendly. Thanks.

**Comment by fabiospampinato** [comment]
Thanks for the suggestion, but I wouldn't like this. It would be a "WTF" moment if you try to start a terminal and suddenly you have a new file you didn't ask for 🤔 

I don't think running the `Terminals: Edit Configuration` command is too bad.

Thanks anyway.

**Comment by yangshuairocks** [comment]
Thanks for the explanation.
