### ISSUE TITLE
Terminal visibility issue following VS Code update to Version 1.17.0 (1.17.0)

### ISSUE THREAD

**Issue by jajohnso** [fabiospampinato/vscode-terminals#2]
Running a new terminals command opens a new terminal, but the command prompt is not visible until interacting with some other panel on the application.

**Comment by fabiospampinato** [comment]
The related upstream issue should be https://github.com/Microsoft/vscode/issues/35728. Let's way for an answer from VSC's maintainers.

**Comment by jajohnso** [comment]
Great. Thanks for the speedy response. Great extension by the way. It's an incredible timesaver.

**Comment by jajohnso** [comment]
Looks like this issue was resolved with release 1.17.2.
