### ISSUE TITLE
Icons in terminal list dropdown

### ISSUE THREAD

**Issue by ProLoser** [fabiospampinato/vscode-terminals#22]
![image](https://user-images.githubusercontent.com/67395/55921454-a198de80-5bb1-11e9-8180-0e82c27270da.png)

I added icons to my terminal configurations, but was a little disappointed that the only place they show up are when you use the `terminals.runSingle` command. It would be nice if I could see these icons in the terminal switcher, or anywhere in the UI when switching between active terminals.

**Comment by fabiospampinato** [comment]
Not possible, an svg image can't be rendered in selects elements, and an icon can't be added elsewhere in the UI where you might want to switch terminals. 

You might want to use emojis or perhaps unicode icons instead.
