### ISSUE TITLE
Cwd throws an error when using variable substitution in 1.12.5

### ISSUE THREAD

**Issue by brian-mann** [fabiospampinato/vscode-terminals#26]
I currently use this configuration...

```js
{
  "name": "packages/server test-e2e",
  "focus": true,
  "onlySingle": true,
  "execute": false,
  "cwd": "[cwd]/packages/server",
  "command": "npm run test-e2e -- --spec name"
},
```

As of `1.12.5` this now throws an error that `cwd` doesn't exist. Likely due to not applying the variable substitution prior to checking if the path exists.

**Comment by fabiospampinato** [comment]
My mistake, fixed in v1.12.6, thank you.
