### ISSUE TITLE
The (not) provided cwd path doesn't exist

### ISSUE THREAD

**Issue by scriptninja** [fabiospampinato/vscode-terminals#27]
With today's update on an insiders build, I get the error

> The provided cwd path doesn't exist

for what seems to be all configurations. None of my configurations specify cwd at all (which worked fine yesterday).

**Comment by fabiospampinato** [comment]
This should be fixed in v1.12.6, are you on v1.12.5 instead?

**Comment by scriptninja** [comment]
Looks like I am. 1.12.6 isn't showing as an available update for me yet. Thanks.

**Comment by fabiospampinato** [comment]
@scriptninja Reload the app, sometimes it happens to me too.
