### ISSUE TITLE
Version 1.12.6 isn't showing as an available update for non-insider build making this plugin unusable

### ISSUE THREAD

**Issue by promethyttrium** [fabiospampinato/vscode-terminals#28]

**Comment by fabiospampinato** [comment]
Reload VSCode, this isn't an issue with the extension itself, results are cached too aggressively inside VSC.

**Comment by promethyttrium** [comment]
Reloaded multiple times.

**Comment by fabiospampinato** [comment]
I think I might have forgotten to publish the update! Sorry about that. 

Are you sure v1.2.6 was available in the insiders build? I don't see how that could happen 🤔

**Comment by fabiospampinato** [comment]
Btw why are you loving your own comments? That's a bit weird.

**Comment by promethyttrium** [comment]
LOL Sorry about that. I was trying to thumbs down your previous comment -- selected the wrong comment and the wrong emoji. By the way, right after that, I see the update in the marketplace, it seems to be working now. Thanks!

**Comment by fabiospampinato** [comment]
Thanks for reporting the issue 👍
