### ISSUE TITLE
Auto clear the screen in bash environment

### ISSUE THREAD

**Issue by shivapoudel** [fabiospampinato/vscode-terminals#29]
My bash setting is like this now:

```json
{
  "autorun": false,
  "terminals": [
    {
      "open": true,
      "name": "WPForms",
      "command": "cd /d/htdocs/wpforms/wp-content/plugins && clear"
    },
    {
      "open": true,
      "name": "Everest Forms",
      "command": "cd /d/htdocs/wpeverest/wp-content/plugins && clear"
    }
  ]
}
```

How can I if I enable `autorun` and have more than 1 terminals, I am receiving unmanaged canvas in the terminal? CTRL+L clears the screen and this works with autorun but how that keymap be implemented or this extension has a certain configuration?

![image](https://user-images.githubusercontent.com/3774827/60999848-d7e62580-a37b-11e9-9829-558f60e09760.png)

**Comment by fabiospampinato** [comment]
Sorry I'm having difficulties trying to understand what you are saying.

From the screenshot it seems that the terminal hasn't been rendered correctly? It shouldn't be centered that way I believe.

**Comment by shivapoudel** [comment]
@fabiospampinato if `autorun` is enabled then the terminal is not being rendered properly. Because multiple terminals needs to be opened. Next thing, if I disabled autorun and open vai shortcut CTRL+ALT+T then it is opened perfercly but also have to use clear command. See the settings I have used currently above.

**Comment by fabiospampinato** [comment]
It seems to be an issue with VSCode, we have no control of how the terminal is actually rendered on screen.
