### ISSUE TITLE
Error running "Terminals: Run"

### ISSUE THREAD

**Issue by sketchbuch** [fabiospampinato/vscode-terminals#34]
Ext v1.12.6
VSC v1.40.0

I get an error when running the command "Terminals: Run"

'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true')

This doesn't seem to stop even after restarting vsc

**Comment by sketchbuch** [comment]
![Bildschirmfoto 2019-11-08 um 10 18 23](https://user-images.githubusercontent.com/16445037/68464776-7c388580-0211-11ea-8aab-a846fbfc4a1a.png)

**Comment by immunity20** [comment]
same here after updating to VSCode 1.40
'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true')
