### ISSUE TITLE
terminals.editConfig not found

### ISSUE THREAD

**Issue by hanct** [fabiospampinato/vscode-terminals#36]
Visual Studio Code: 1.40.1
Extension version: 1.12.8

Via the command palette, I run the  Terminals:EditConfiguration, but got error "terminals.editConfig not found" instead. Is there something i did not do correctly?

**Comment by fabiospampinato** [comment]
Looks like a bug.

**Comment by fabiospampinato** [comment]
Updating the extension fixed the issue I experiences.

Can you give me more details about yours? Are you seeing any other errors?

**Comment by hanct** [comment]
> Updating the extension fixed the issue I experiences.
> 
> Can you give me more details about yours? Are you seeing any other errors?

Hi, yes, it is in the command palette. Upon choosing it in the palette, I encounter this error but no other details.  
Nevertheless, i try to restart the vscode, then the issue is RESOLVED. So i suspect installing this extension need to restart vscode, otherwise will encounter the error.
