### ISSUE TITLE
"The provided cwd path doesn't exist" is obscure

### ISSUE THREAD

**Issue by pbrit** [fabiospampinato/vscode-terminals#37]
There should be at least the basename of the provided `cwd`. 

Related Issues: #27 #26 #15 #14

**Comment by fabiospampinato** [comment]
How is obscure? I don't understand what you're asking for here, what's the basename of the provided cwd?

**Comment by pbrit** [comment]
> How is it obscure? I don't understand what you're asking for here, what's the basename of the provided cwd, could you give me a practical example?

The issue here is as follows: "The provided cwd path doesn't exist" doesn't contain the actual path which supposedly doesn't exist. 

Imagine a big multi-root workspace where each project has a bunch of terminals configured. If just one terminal has a misconfigured `cwd`, it's a lot hassle to find which terminal is at fault.

Please take a look at #39, feel free to change the message as long as it contains the actual path to `cwd` .
