### ISSUE TITLE
Fearue request: rename the terminal to the corresponding name

### ISSUE THREAD

**Issue by Aminadav** [fabiospampinato/vscode-terminals#38]
I think it should be pretty easy.
To give the terminal the name of the command in the terminals.json.

![image](https://user-images.githubusercontent.com/3584317/71570449-c1748780-2add-11ea-8272-e923b707c08f.png)

This is VS code to rename terminals, so just executing it automatically.

@fabiospampinato  What do you think?

BTW, I'm a 1 day user of the extension and really like it.

**Comment by fabiospampinato** [comment]
Like you want your terminal to be called "npm start" rather than "node"?

I'd say just setting the `name` property would be better.

**Comment by Aminadav** [comment]
I'm saying to give the terminal in vs code, the same new I gave in the terminals.json file.

**Comment by fabiospampinato** [comment]
It already works like that, can you post your configuration?
