### ISSUE TITLE
are global settings possible ?

### ISSUE THREAD

**Issue by ffred** [fabiospampinato/vscode-terminals#4]
Hi,
is it possible to set global settings for "vscode-terminals" if I want to have the same commands in every projects ?
thanks.
Fred

**Comment by ffred** [comment]
sorry, asked too fast. just saw on terminals documentation that I can set a custom path for the setting file.
could probably do some kind of global setting like that.

**Comment by fabiospampinato** [comment]
Exactly, that way **every** terminal would be global.

I'm not 100% sure, but I think you can also define terminals in your global VSC settings file. This way you would have some global terminals as well as local terminals if you need them.

**Comment by ffred** [comment]
thanks.. gonna make some tests.

**Comment by fabiospampinato** [comment]
I forgot to mention that those terminals defined in the settings should be defined under the `terminals.terminals` key.

**Comment by ffred** [comment]
I tried that, but as I saw the "Unknown configuration setting" message, I didn't really launch a command.
tried again and when I launch a command it seems to work ok, even with the "unknown.." message.
good. will verify later with some other terminals command on another project.
thanks a lot for your work.

**Comment by fabiospampinato** [comment]
You get that error because the extension doesn't properly tell VSC that it supports that option, I'll fix this as well.

**Comment by ffred** [comment]
sorry to give you all that work today.. :-)

**Comment by fabiospampinato** [comment]
No problem, I like to improve my extensions :)

**Comment by fabiospampinato** [comment]
This should be fixed in v1.5.3.

There was the ability to add global terminals, but if you did, you couldn't have local terminals. It should work properly now.

**Comment by ffred** [comment]
global and local settings working good, thanks !! 👍  :-)
