### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by ukozdan** [fabiospampinato/vscode-terminals#42]
In [the Terminals Manager documentation](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals), under "Configuration", it describes the following commands
```
"onlySingle": true, // Don't run this with the `Terminals: Run` command
"onlyMultiple": true, // Hide it from the `Terminals: Run Single` command
"onlyAPI": true, // Don't run this with the `Terminals: Run` command and hide it from the `Terminals: Run Single` command
```
I don't understand what these commands do. Perhaps some simple step-by-step instructions would reduce the amount of issues raised.

**Comment by fabiospampinato** [comment]
Play with those a bit to understand them better.

Initially this extension was created to spawn up a bunch of terminals at once, then I added the "Terminal: Run Single" command, those are switched for telling the extension if a particular terminal should be spawned with all the others, or it should be spawned only via that command I mentioned, of if it's only available via VSCode's APIs.

**Comment by lonix1** [comment]
I only want the terminals opened on vscode load (not "Run" or "Run single").

So I used `"onlyAPI": true` and it complains:
> No terminals defined, edit the configuration

If I remove that setting then it works, but of course it also works with "Run" and "Run single", which I don't want.

Any advice?

**Comment by fabiospampinato** [comment]
Run will run terminals defined to run at startup, you can't both have terminals defined to run at startup and them not run when you execute the Run command, that's what it does.
