### ISSUE TITLE
Possibility to add configuration to workspace configuration

### ISSUE THREAD

**Issue by marioxcolomar** [fabiospampinato/vscode-terminals#48]
Having searched for a possibility to add a terminal for each folder/directory in my workspace I came across Terminals. Great tool! Great solution! Just missing one thing. Currently I made a configuration that adds a terminal for each of the folders I have in my workspace. Unfortunately the configuration file is added to one of my projects. Meaning I have to commit the file or it will forever appear in my source control tab. Ideally you could add a "terminals" prop to the workspace json file.

```
{
 "folders": [
  {
   "name": "project_one",
   "path": "project_one"
  },
  {
   "name": "project_two",
   "path": "project_two"
  }
 ],
 "terminals": [
  {
    "name": "project_one",
     "focus": true,
     "cwd": "~/project_one"
  },
  {
     "name": "project_two",
     "focus": false,
     "cwd": "~/project_two"
   }
 ]
}
```

I left out the autorun from the configuration as this will have to be handled differently but the above example is just for illustration.

You could ideally add the terminal boolean for each folder, but that could be a VS Code limitation.

**Comment by fabiospampinato** [comment]
That should be already implemented, write your configurations inside the "terminals.terminals" setting.

**Comment by marioxcolomar** [comment]
Can you provide an example of a workspace file with the "terminals.terminals" setting?

**Comment by fabiospampinato** [comment]
I think you should be able to just define terminals under that setting key, rather than under the "terminals" key in the standalone "terminals.json" file.

**Comment by marioxcolomar** [comment]
thanks @fabiospampinato
