### ISSUE TITLE
start a new python virtual environment and run commands

### ISSUE THREAD

**Issue by kshishir** [fabiospampinato/vscode-terminals#50]
I am trying to start a new python virtual env for my backend flask app. The second command does not run. 
Is there a way to run the command in the new shell. 
Here is my terminal config:
```
{
        "name": "python-flask-start", 
        "description": "local python flask start",
        "cwd": "backend",
        "commands": [
          "pipenv shell",
          "python flask.py"
        ]
      }
```

**Comment by fabiospampinato** [comment]
This extension isn't really able to handle that use case, and I'm not sure it could support it without breaking other things. 

You should try to modify the "pipenv shell" command to execute a command directly, maybe it has a "-c" option that allows you to specify the command directly or something
.
