### ISSUE TITLE
is there a way actually to use vscode variable substitution in a command ?

### ISSUE THREAD

**Issue by ffred** [fabiospampinato/vscode-terminals#6]
Hi,
tried different thing, but didn't find a way to use vscode [variable substitution](https://code.visualstudio.com/docs/editor/debugging#_variable-substitution) in a command, like ${cwd} or ${fileBasename}..
is there a way to do that actually or not ?
thanks.
Fred

**Comment by fabiospampinato** [comment]
It isn't currently implemented, no.

What's the use case for this? Generic global terminals?

**Comment by ffred** [comment]
yes.. but I will do it differently, no problem. I think I could do it from the Commands extension or eventually via the call of a Batch file.
thanks..

**Comment by fabiospampinato** [comment]
No problem.

I'm keeping this open though, it seems to be an interesting addition.

**Comment by fabiospampinato** [comment]
Implemented in v1.8.0.

**Comment by ffred** [comment]
nice, thanks !!
