### ISSUE TITLE
Icon won't change on list

### ISSUE THREAD

**Issue by Hakkahi** [fabiospampinato/vscode-terminals#60]
VSCode v1.60.0
Terminals manager v1.12.10
Windows 10

I tried to change the icon using the icon property (i.e: "icon": "alert") but the icon did not change.
No errors are triggered and my terminal is starting fine.
Am I doing something wrong or is it a bug?

![image](https://user-images.githubusercontent.com/5653683/132867650-1d358d3c-b297-476e-9f30-eaeca7e47dca.png)

**Comment by eboboshka** [comment]
Same

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Comment by rbalet** [comment]
@fabiospampinato This issue can be closed since it's working now
