### ISSUE TITLE
Run "nvm use"

### ISSUE THREAD

**Issue by sketchbuch** [fabiospampinato/vscode-terminals#61]
I have a terminal setup to run "nvm use" and have "autorun": true in my config. This works fine, when I switch to the workspace the terminal is run and the correct node version used. Is there any way to specify that nvm use should be run in every terminal, including those created voa VSCode's new terminal comnmand? I want every terminal to switch to the correct node version

**Comment by fabiospampinato** [comment]
I'm not sure 🤔 Anyway this isn't strictly related to the extension, if you open terminals manually this extension doesn't control them.
