### ISSUE TITLE
Terminal names intermittently go blank when using "Focus next terminal group" keyboard shortcut

### ISSUE THREAD

**Issue by gbny** [fabiospampinato/vscode-terminals#64]
- I can only reproduce when a set of terminals has been opened by the "Terminals: Run" command
- Only happens (intermittently) when using the "Focus next terminal group" keyboard shortcut
- Clicking in the terminals list or in the active terminal fixes the titles display
- I love this extension, thanks for making it @fabiospampinato !!!!
![image](https://user-images.githubusercontent.com/98421618/151042367-0e552838-ee4d-4ee7-ac4e-9af7beac1ec5.png)

**Comment by fabiospampinato** [comment]
That looks like an issue with vscode itself.
