### ISSUE TITLE
Allow executing a terminal using a keyboard shortcut

### ISSUE THREAD

**Issue by akaibukai** [fabiospampinato/vscode-terminals#65]
Hello and thank you for your plugin.

Is it possible to set a keyboard shortcut to a given `Run Single` command?

My usage of this plugin is like that:

- I have a set of terminals that are "persistent": I run them at startup using `"autorun": true,` and having `"onlyMultiple": true` so that they don't appear when running a single command.
- Then I have a bunch of terminal `"onlySingle": true` that I dispatch on the previous terminals using the `target` option,
- Now, it'll be very good if I can "launch" a given terminal (that is basically acting as a _Task_ in my usage)

I am used to run my tasks with _VSCode Tasks_ but your plugin make me integrate them in existing terminals which I like.

Currently, it's still efficient since I'm using `Ctrl+Shift+T` and then I only have displayed my `onlySingle` terminals.

Thank you very much.

Edit: Just discovered your Commands plugin (which I also open an [issue (related to Remote Container)](https://github.com/fabiospampinato/vscode-commands/issues/41). And it could be great if you can also add a shortcut feature to Commads when wanting to use with Terminals Manager.

**Comment by fabiospampinato** [comment]
Unless it's buggy it should be already supported, in vscode-commands' readme there's an example of how to do this:

```json
{
  "text": "$(terminal)",
  "command": "terminals.runTerminal",
  "tooltip": "Run a terminal"
},
{
  "text": "Init",
  "command": "terminals.runTerminalByName",
  "arguments": ["init"],
  "tooltip": "Init the project"
},
{
  "text": "Serve",
  "command": "terminals.runTerminalByName",
  "arguments": ["serve"],
  "tooltip": "Serve the project"
}
```
