### ISSUE TITLE
No terminals defined error, edit the configuration

### ISSUE THREAD

**Issue by jasonbronson** [fabiospampinato/vscode-terminals#67]
Version: 1.66.2 (Universal)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z (1 wk ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 20.3.0

Newly installed and setup a terminals.json file

`{
  "autorun": true,
  "terminals": [
    {
      "name": "Dashboard",
      "open": true,
      "onlySingle": true,
      "cwd": "/root/www/dashboard",
      "persistent": "dashboard",
      "command": "npm run serve"
    }
  ]
}`

**Comment by bart-antczak** [comment]
Remove "onlySingle": true

**Comment by fabiospampinato** [comment]
@bart-antczak's answer is correct, if you use "onlySingle" then that terminal won't be opened automatically.
