### ISSUE TITLE
Option to open the panel 

### ISSUE THREAD

**Issue by Mattias-Martens** [fabiospampinato/vscode-terminals#70]
Hi, this is a really great extension!

My suggestion is: when opening terminals from the command palette (or possibly on autorun with VSCode window opening——discuss?) it would be helpful (and match the expectations created by VSCode's default behaviour) if the Terminal View opened if it was not open already.

This is the view toggled with command `workbench.action.terminal.toggleTerminal`.

**Comment by fabiospampinato** [comment]
Actually there's basically an option for this already, if you set the `"open"` option for your terminals to true that's what will happen already. I don't think we need another global option that does the same thing.
