### ISSUE TITLE
[Question] Comparison to built-in feature?

### ISSUE THREAD

**Issue by lonix1** [fabiospampinato/vscode-terminals#72]
I found this extension, but I also [this](https://code.visualstudio.com/docs/editor/integrated-terminal#_automating-launching-of-terminals) built-in feature.

Does someone know how they differ, and if this extension adds more functionality?

Basically I want to open a number of terminals when I open vscode. Each one in a separate directory.

**Comment by Mattias-Martens** [comment]
at a glance the main difference is that the built-in feature does not support custom icons and colors: https://github.com/microsoft/vscode/issues/130070

on the other hand this extension does not support creating groups; and neither feature supports creating terminals with split panes.

for your use case i don't think you will find much difference. to me, built-in tasks looks a bit cumbersome compared to the scheme of terminals.json, but that's about it.

**Comment by fabiospampinato** [comment]
I see this extension mainly as a mean to set-up some terminals automatically, and as a way to spawn one-off terminals quickly. I don't think the built-in terminal supports these features? Other than that there are only small differences I think.
