### ISSUE TITLE
How to run commands containing strings?

### ISSUE THREAD

**Issue by SurajMeena** [fabiospampinato/vscode-terminals#73]
How can I run commands like `Get-Process | Tee-Object - FilePath "results$((get-date).ToString("MM-dd-yyyy"))` or for that matter functions with multiple lines?
I couldn't find any example for usage of global env variables as well. Is it possible to add that in documentation?

**Comment by SurajMeena** [comment]
> 
How can I run commands like Get-Process | Tee-Object - FilePath "results$((get-date).ToString("MM-dd-yyyy"))
I got answer to this part from the demo file that comes when you first run terminal: edit configuration. So we can use backslash to escape inverted commas. I am still curious how multiline commands can be written maybe backslash would work for them as well.

**Comment by fabiospampinato** [comment]
I think perhaps if you want to write newlines you have to write the escape sequence for that: `\n`, which encoded inside JSON becomes: `\\n`.
