### ISSUE TITLE
Icon & Color configuration don't work in VScode Version: 1.70.0 (Universal)

### ISSUE THREAD

**Issue by JacobsonGal** [fabiospampinato/vscode-terminals#76]
The icon and color configurations don't work, the opened terminals are with the VScode terminal default icon and color...

**Comment by JacobsonGal** [comment]
add "terminal.integrated.shellIntegration.enabled": false to vscode settings for the icons and colors to work 👍

**Comment by sixclones** [comment]
@fabiospampinato do you know if there is a reason that shell integration makes icons and colors not working? Could be nice to have both.

**Comment by fabiospampinato** [comment]
@sixclones VS Code might be setting those after the extension has already set them, I should look into this.
