### ISSUE TITLE
[Question] Split terminals

### ISSUE THREAD

**Issue by MarcosValens** [fabiospampinato/vscode-terminals#78]
Is it possible to open two terminals in split screen? if possible, how is it done? if it is not possible, it could be implemented. I add an example capture.
![image](https://user-images.githubusercontent.com/33330492/194346336-594dc586-4ea2-412f-bcde-5bb1c76970a7.png)

**Comment by globalhuman** [comment]
This seems to be already covered by https://github.com/fabiospampinato/vscode-terminals/issues/9

**Comment by fabiospampinato** [comment]
Duplicate of #9
