### ISSUE TITLE
icon documentation/demo

### ISSUE THREAD

**Issue by ddurschlag6river** [fabiospampinato/vscode-terminals#8]
I have not been able to get the icon configuration option to work. The code is also a mystery to me -- I can't find any docs on what $() does in a template string. An example or reference documentation would both be great (maybe an example in the default demo config?).

**Comment by fabiospampinato** [comment]
The `$(icon-name)` bit is a VSC thing, which I believe is not documented anywhere, I had opened an [issue](https://github.com/Microsoft/vscode-docs/issues/1094) about this, but it hasn't been addressed yet.

I've added a paragraph explaining how to use icons, you can find it at the bottom of the readme.

Let me know if you have any other problems.

**Comment by gkoulin** [comment]
I don't see an icon following your insturctions. Where is it suppose to appear?
