### ISSUE TITLE
When VS Code reloads window, it recreates same terminals, they become duplicated 

### ISSUE THREAD

**Issue by Kenya-West** [fabiospampinato/vscode-terminals#85]
I have config as follows:

```json
{
  "autorun": true,
  "terminals": [
    {
      "name": "NPM: Start (dev)",
      "description": "Runs NPM start with development configuration",
      "onlyMultiple": true,
      "icon": "loaded-scripts-view-icon",
      "command": "npm run start:dev"
    },
    {
      "name": "CLI: Angular",
      "split": "NPM: Start (dev)",
      "onlyMultiple": true,
      "focus": true,
      "execute": "npx ng g"
    }
  ]
}
```

This creates splitted terminals on VS Code's launch.

When I update extensions, update VS Code itself, or do whatever action that causes VS Code's window to reload - it recreates these terminals again. Even when old ones were restored already by the moment. So they become duplicated.

P. S. When I do `> Terminals: Run` command, the extension do not create terminal if it exists.

**Comment by besseddrest** [comment]
I had this problem too, this solution worked for me in a similar/duplicate issue: https://github.com/fabiospampinato/vscode-terminals/issues/63#issuecomment-1021520652
