### ISSUE TITLE
Option as to whether individual terminal window should be run

### ISSUE THREAD

**Issue by U-4-E-A** [fabiospampinato/vscode-terminals#87]
I am working with a monorepo and sometimes I don't want to have certain terminal windows open i.e. I could be working on the back-end for weeks and do not want terminal windows for the front-end opened (time, clutter).

AFAIK there is no option for this but I would like the ability to keep the setting for certain windows in `terminals.json` yet not have them open. An `ignore` option (defaulted to `false`) would be great: -

```
{
  "terminals": [
    {
      "name": "Whatever",
      "ignore": true,
      [...]
    },
    [...]
  ]
}
```

Great extension BTW. Couldn't live without it.

**Comment by fabiospampinato** [comment]
You could temporarily comment those out potentially. A better solution might be supporting groups, presumably. Let's track that here: https://github.com/fabiospampinato/vscode-terminals/issues/12
