### ISSUE TITLE
Question: Disable default terminal when using terminals manager

### ISSUE THREAD

**Issue by fjunk** [fabiospampinato/vscode-terminals#89]
Hi! 
I just started using terminals manager and ran into an "issue": 

Whenever I close and restart the IDE, some kind of "default terminal" is also created in addition to the one defined in the _terminals.json_ file. Is there any config i have to set in either vscode or the terminals manager config to disable this behaviour? 

Couldn't find a working solution. My current config looks like this: 
```json
{
  "autorun": true,
  "terminals": [
    {
      "focus": true,
      "name": "sensor-station",
      "description": "This is a description",
      "color": "terminal.ansiRed"
    }
  ]
}
```
those two are then created: 
<img width="278" alt="image" src="https://github.com/fabiospampinato/vscode-terminals/assets/8605033/58c7d7e7-e916-4761-adbc-f6badb099461">

Any help would be appreciated! :)

**Comment by fabiospampinato** [comment]
As far as I know vscode never add a setting for this 🤔 Maybe the extension could close all terminals at startup time, but it would be a bit inaccurate, and  it wouldn't work as well as if vscode just didn't restore the terminal.

**Comment by fabiospampinato** [comment]
Ah nevermind, these settings seem to fix it:

```json
  "terminal.integrated.persistentSessionReviveProcess": "never",
  "terminal.integrated.hideOnStartup": "always",
```

**Comment by fjunk** [comment]
Thanks a lot for the investigation! :)

**Comment by Stan-Stani** [comment]
Note that even if you have `  "terminal.integrated.enablePersistentSessions": false,` you still need

```json
 "terminal.integrated.persistentSessionReviveProcess": "never",
  "terminal.integrated.hideOnStartup": "always",
```
